[build-system]
requires = [
    "setuptools >= 42",
    "wheel",
#    "cython >= 3.0.0a9",
    "versioneer-518"
]
build-backend = "setuptools.build_meta"


[tool.black]
exclude = 'PyMCTranslate/json'
